# version:   "0000--11-Sep-2022"
copyright:   "2022"
author:      "Raphael Fide Christano"
name:        "Raphael Fide Christano"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/fideraphael/os222"
myloglink:   "/TXT/mylog.txt"